spring:
  datasource:
    url: "jdbc:mysql://localhost/commuting_system"
    username: "root"
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jap:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect